// import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// // This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */
// const sidebars: SidebarsConfig = {
//   bookSidebar: [
//     {
//       type: 'doc',
//       id: 'index',
//       label: '📖 Book Home',
//     },
//     {
//       type: 'category',
//       label: '📘 Module 1: The Robotic Nervous System (ROS 2)',
//       collapsed: false,
//       items: [
//         'module-1-ros2/index',
//         'module-1-ros2/ch01-intro-physical-ai',
//         'module-1-ros2/ch02-ros2-architecture',
//         'module-1-ros2/ch03-ros2-packages',
//         'module-1-ros2/ch04-launch-files',
//         'module-1-ros2/ch05-urdf-robot-description',
//       ],
//     },
//     {
//       type: 'category',
//       label: '🌍 Module 2: The Digital Twin (Gazebo & Unity)',
//       collapsed: true,
//       items: [
//         'module-2-digital-twin/index',
//         'module-2-digital-twin/ch06-gazebo-simulation',
//         'module-2-digital-twin/ch07-unity-rendering',
//       ],
//     },
//     {
//       type: 'category',
//       label: '🤖 Module 3: The AI-Robot Brain (NVIDIA Isaac)',
//       collapsed: true,
//       items: [
//         'module-3-isaac/index',
//         'module-3-isaac/ch08-isaac-sim',
//         'module-3-isaac/ch09-isaac-ros',
//         'module-3-isaac/ch10-nav2-planning',
//       ],
//     },
//     {
//       type: 'category',
//       label: '🗣️ Module 4: Vision-Language-Action (VLA)',
//       collapsed: true,
//       items: [
//         'module-4-vla/index',
//         'module-4-vla/ch11-voice-to-action',
//         'module-4-vla/ch12-cognitive-planning',
//         'module-4-vla/ch13-capstone',
//       ],
//     },
//     {
//       type: 'category',
//       label: '📚 Appendices',
//       collapsed: true,
//       items: [
//         'appendices/appendix-a-hardware',
//         'appendices/appendix-b-installation',
//         'appendices/appendix-c-api-reference',
//         'appendices/appendix-d-resources',
//       ],
//     },
//   ],
// };

// export default sidebars;






import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
